### ISSUE TITLE
No package.json

### ISSUE THREAD

**Issue by dotgrid** [Fr3akyMurk/Cloudflare-bulk-dns-delete#1]
I'd love to use this but I don't think all the files are in the repo?

**Comment by Fr3akyMurk** [comment]
Hello.
My bad, I've included the package.json file now, it's only one module that is required.
It should stop complaining after you run `npm i request` in the same folder.

I should remind you that to make it properly work you have to fill in the data fields otherwise it will try to delete data from something that doesn't exist.
